### ISSUE TITLE
Please add function.

### ISSUE THREAD

**Issue by Osamushi** [wagiro/BurpBounty#10]
Hi wagiro!

This plugin is amazing!

I want to select the position of insertion point  at  after parameter value like "Burp Intruder ".
Because I would like to compare responses as follows when testing SQLi. 

For example

requestA
parameterA = value ' and 'a' = 'a

responseA
normal response

requestB
parameterA = value ' and 'b' = 'a

responseB
error response

Please add above function.

**Comment by egarciamelia** [comment]
Hi @Osamushi !

Thanks for your comments. It's not in my mind to add that function for now. I am working on version 2.0 that will have many improvements.

What you can do is, Request B for detect the error automatically with the extension, and once detected make the Request A for normal response by hand, so compare the results.

Regards!
