### ISSUE TITLE
Bug: BurpBountyGui line 658:Cannot invoke "String.equals(Object)" because "this.timeOut" is null

### ISSUE THREAD

**Issue by a-marionette** [wagiro/BurpBounty#102]
Hello,

Receiving this error when running a single BB profile used to check for a sleep threshold.  I believe this issue may occurs as a result of a "Null Timeout" (No response from server). See the Logger extension image below for an example.

![Screen Shot 2021-03-16 at 12 42 12 AM](https://user-images.githubusercontent.com/16928471/111272936-74040d80-85f0-11eb-8478-ffade4b17144.png)

"BurpBountyGui line 658:Cannot invoke "String.equals(Object)" because "this.timeOut" is null"

**Comment by wagiro** [comment]
Solved in version 4.0.
