### ISSUE TITLE
Burp Bounty free edition not detecting anything

### ISSUE THREAD

**Issue by mr-n30** [wagiro/BurpBounty#104]
Hello,

After following along on your YouTube video here: https://www.youtube.com/watch?v=JR2hbgYFhME I wasn't able to get your extension to work. I followed along step by step, clicking on the exact tabs and inserting the same payloads as in the video. I then visited a bug bounty website that's running WordPress and the extension didn't detect anything. Viewed the source of the website to make sure it contains wp-content just to double check. I also tried removing and installing the extension again to see if that fixed the issue and nothing still. This is my first time trying out your tool too.

I'm using Burp Suite Pro on Linux.

**Comment by Lucisu** [comment]
Same here

**Comment by wagiro** [comment]
Hi!

What version of java are you using? many times with versions older than jdk14 or openjdk 19 it doesn't work well.

Thanks,
Best regards.
