### ISSUE TITLE
Request option to run burp bounty scan alone

### ISSUE THREAD

**Issue by marcelo321** [wagiro/BurpBounty#106]
As there are options to run extensions alone, would be really helpful to have an option to run burp bounty scan alone, without any of the different extensions we have.

As I tried a running extension only scan in a request with only 1 parameter it wasn't detecting a simple xss after 5k requests...

Burp pro has the option to run, parameter miner, turbo intruder, upload scanner, etc. alone. Why burp bounty doesn't have this?

**Comment by wagiro** [comment]
Hi!

This option is in the Burp Bounty Pro (I have developed the whole topic of threads and concurrency, since the burpsuite API does not allow to do that).

Thanks,
Best regards.
