### ISSUE TITLE
Losing configuration after closing burp

### ISSUE THREAD

**Issue by marcelo321** [wagiro/BurpBounty#108]
Hello,

I noticed I lost everything I configured after closing burp professional. All the new templates and the ones I modifed are gone.

Is there a way to automatically save this? and to save it manually? I was thinking of buying the pro version but this free version is giving me more trouble that benefits

**Comment by wagiro** [comment]
Hi @marcelo321 !

What configuration have you lost? in burp bounty free the only configuration there is is the directory.

I have not answered before because I was developing version 4.0 of Burp Bounty Free. In it are many of the bugs fixed in case that you want try it.

Thanks,
Best regards.
