### ISSUE TITLE
Burp v2.0.08 - compatibility

### ISSUE THREAD

**Issue by Teicu** [wagiro/BurpBounty#11]
I think there is a problem, because I fail to save any profile, I tried countless times but useless. 

I press the  "Save " button But nothing happens, I see no errors in the Extender 

Thank you

**Comment by wagiro** [comment]
Hi @Teicu ,

You have to specify the directory where the profile will be saved and make sure you have write permissions.


Tell me if you still can not save the profiles.

Thank you,
Greetings.

**Comment by Teicu** [comment]
You are absolutely right.  My mistake because I forgot to add the profile directory 

Works like a charm now 👍 


Thank you very much!

**Comment by wagiro** [comment]
Perfect! 👍
