### ISSUE TITLE
Adding Authorization Bearer Tokens

### ISSUE THREAD

**Issue by louisatrhymetec** [wagiro/BurpBounty#117]
It's not super clear how you can add authorization bearer token to every payload. Typically, with the built-in scanner you can use Macros to scoped to URL and use of built in scanner. It's probably not ideal to have it scoped to URL and extensions... Some documentation for this would be appreciated.

**Comment by wagiro** [comment]
Hi @louisatrhymetec ! Sure, I will implemente one thing soon. Thanks!
