### ISSUE TITLE
open redirect config

### ISSUE THREAD

**Issue by Teicu** [wagiro/BurpBounty#12]
Hi, can you help me please to configure the open redirect? Thank you     

I got a lot of false positive using it even if I configure it like you did on youtube tutorial 

<img width="1414" alt="screen shot 2018-10-19 at 08 46 47" src="https://user-images.githubusercontent.com/1572822/47199711-8e802100-d37b-11e8-9368-429c2ed3fabe.png">
 

thank you

**Comment by wagiro** [comment]
HI @Teicu,

With this config its possible that you have false positives, because it's possible that the application return you regex but first another domain, it's your case?

If you want tell me more details about it, we can see if its possible resolve this.

Thanks for comment!
