### ISSUE TITLE
Add new payload encoder - replace string

### ISSUE THREAD

**Issue by virusvfv** [wagiro/BurpBounty#13]
Sometimes we have to replace some strings in payloads. For ex: replace /etc/passwd to /etc/resolv.conf to bypass IPS or WAF, or replace evilsite.com to blabla.burpcollaborator.com to testing blind vulns.
So replace string encoder or something like this would be very useful.
As example U can refer to my commits to burpbounty v1 forks in my github...
Once more thanks for such tool !

**Comment by wagiro** [comment]
Hi @virusvfv!

I think it could be useful. I'll put it in the roadmap of the next version.

Thanks for everything!

PS: Could I put a link in my github to your Burpbounty profile of your github?

**Comment by virusvfv** [comment]
Yes of course...

**Comment by wagiro** [comment]
Done!
