### ISSUE TITLE
Wrong profile swithcing in Profile manager

### ISSUE THREAD

**Issue by virusvfv** [wagiro/BurpBounty#16]
When I sort profiles in Profile Manager and then try to  enable/disable some of sorted profile -  BB switches non-selected profile, but some other profile (i suppose BB switch profile that was on selected place before sorting :) )

**Comment by wagiro** [comment]
Hi @virusvfv !

Solved! At the moment not is possible sort profiles, in next version will be sortable.

Thanks!

PS: I would like to thank you in the github, could you give me the information you want to show? email, twitter, github ...

**Comment by wagiro** [comment]
Hi @virusvfv !

I solved this question in version 2.3, as you can see in:

https://github.com/wagiro/BurpBounty/wiki/usage

Now in Profiles Manager, you can specified the twitter author, and sort, delete multiples profiles, etc.

Thanks :D
