### ISSUE TITLE
Bindsqli-contentlength has too many errors

### ISSUE THREAD

**Issue by 7e1** [wagiro/BurpBounty#19]
![image](https://user-images.githubusercontent.com/8321329/49422341-769b1a00-f7ce-11e8-8719-36e71cdbc088.png)

it should be compared twice:
1. http://testphp.vulnweb.com/artists.php?artist=1
2. http://testphp.vulnweb.com/artists.php?artist=1 and 1=1
3. http://testphp.vulnweb.com/artists.php?artist=1 and 1=2

1=2    1!=3

**Comment by wagiro** [comment]
Hi @7e1 !

The Content-Length match option, compare the original request with the request with payloads. 

I modified the profile a bit to eliminate some false positives. The idea of the profiles is that everyone can adapt them to your liking, this is the power of the extension.

Thanks for comment.
Regards!
