### ISSUE TITLE
Requests sent by scanner is not incremented

### ISSUE THREAD

**Issue by karibasavaraj-sec** [wagiro/BurpBounty#21]
Hi Wagiro,

The Scan Check Builder is amazing. 

We used the extender to send payloads through active scan. The Active scan was able to send multiple requests using extender.

However, we noticed that the number of requests sent by scanner is not getting updated. 
 Scanner --> Scan Queue --> Requests. We are using Burp Suite Pro version 1.7.37.

Please could you let us know your comments.

Thanks in advance,
Karibasavaraj K

**Comment by wagiro** [comment]
Hi @karibasavaraj-sec! 

Thanks for your words. This issue is knowed for me, but Im not sure how resolve it. I will ask to burpsuite support team and then, if it's possible, I solve it.

Regards!

**Comment by wagiro** [comment]
Hi @karibasavaraj-sec,

Yes in BurpSuite 1.7.37 the number of request don't update. This issue its solved in BurpSuite 2.0.14beta, can you try in this versión?

Thanks!

**Comment by karibasavaraj-sec** [comment]
Hi wagiro,

I will check it and update.

I have an additional query: We wanted to know the maximum number of payloads that we can provide for a profile. Please can you let us know the limit.
