### ISSUE TITLE
Passive Response Check - CSS and JS

### ISSUE THREAD

**Issue by rknellx** [wagiro/BurpBounty#23]
Hi wagiro,

I am trying to perform a passive response search within .css and .js files using a regular expression; however, I do not obtain any matches. For some reason, I only obtain results when the content-type is text/html. I did not enable the 'Content-Type' check option to specifically search for text/html, so I'm not sure why a match is not occurring. I have also tried changing to a 'Simple Search', rather than use a regular expression, but I am still not having any luck.

**Comment by wagiro** [comment]
Hi @rknellx ,

I will investigate the issue and give you an answer in the shortest time possible.

Thank you!

**Comment by rknellx** [comment]
Ok, thank you for your help!

**Comment by wagiro** [comment]
Hi @rknellx ,

Im my computer works, for example with .js files:

![captura de pantalla 2019-01-23 a las 21 04 39](https://user-images.githubusercontent.com/3398430/51633703-96d79180-1f52-11e9-96e6-a22073a74c56.png)

![captura de pantalla 2019-01-23 a las 21 06 06](https://user-images.githubusercontent.com/3398430/51633772-bbcc0480-1f52-11e9-8bca-19bac83f1be1.png)

![captura de pantalla 2019-01-23 a las 21 05 09](https://user-images.githubusercontent.com/3398430/51633704-96d79180-1f52-11e9-9671-f9d065689809.png)


Can you give me more info about it?

Thanks!

**Comment by rknellx** [comment]
After some further testing, it seems as though issues get populated only after you first run an active scan against a particular resource. Are you experiencing the same behavior?

**Comment by wagiro** [comment]
Hi @rknellx ,

No, it works well for me from the beginning.

My versions are: BurpBounty 3.0.2 and Burpsuite 2.0.14beta

Regards!
