### ISSUE TITLE
Not able to get Instances of Issues in Target Site Map

### ISSUE THREAD

**Issue by karibasavaraj-sec** [wagiro/BurpBounty#24]
Hi wagiro,

I am not able to get Instances of Issues in Target Site Map

I get one Issue as attached.

However, when I go to scanner, I get 4 instances of the Issue. Attached is screenshot

Please can you let me know how can I get Instances of Issues in Target Site Map.

Note: I am running the Active Scan for Extension generated 

Thanks in advance,
Karibasavaraj K

<img width="960" alt="targetsitemap" src="https://user-images.githubusercontent.com/46919944/51691052-036c9200-2020-11e9-9ac4-b643aae46602.png">
<img width="1507" alt="scanner" src="https://user-images.githubusercontent.com/46919944/51691053-036c9200-2020-11e9-8fb3-0f19f505e6fe.png">

**Comment by wagiro** [comment]
Hi @karibasavaraj-sec ,

What version of extension and Burpsuite are you using?

For me, with BurpBounty 3.0.2 and Burpsuite 2.0.14beta works.

<img width="1273" alt="captura de pantalla 2019-01-24 a las 20 18 21" src="https://user-images.githubusercontent.com/3398430/51702921-542abd80-2015-11e9-8a3d-2d73a8226f46.png">

Regards!

**Comment by karibasavaraj-sec** [comment]
Hi wagiro,

I am using BurpBounty 3.0.2beta and Burp Suite Pro version 1.7.37.

Thanks and Regards,
Karibasavaraj K

**Comment by wagiro** [comment]
Hi @karibasavaraj-sec ,

For me in version 1.7.37 works:


![captura de pantalla 2019-01-25 a las 13 08 17](https://user-images.githubusercontent.com/3398430/51745191-6141be00-20a2-11e9-8034-3d63b28dd20c.png)


Regards!
