### ISSUE TITLE
Incorrect handling of Macro requests

### ISSUE THREAD

**Issue by v-p-b** [wagiro/BurpBounty#25]
When configuring post-request macros for the target URL under scan, BurpBounty generates Issues that include the macro request instead of the original request (containing the configured payload).

Example:

Interface A accepts requests, B displays parameter values received by A. In order to identify XSS issues a post-request macro is configured to request B after a scanner request is issued to A. If interface B contains the XSS payload an Issue is generated by BurpBounty, but the HTTP Request associated with the issue is the one for interface B instead of the one issued to A.

**Comment by wagiro** [comment]
Hi @v-p-b ,

Thanks for the issue, can you give me an example of configuration for reproduce the issue? I think that I don't understand the situation.

Regards!

**Comment by v-p-b** [comment]
Suppose there are two interfaces on the target app:

`/input?param=xyz`: stores the value of `param` in a database

`/output`: Displays the last saved `param` (in this example "xyz")

I configure a session handling rule in Burp (under Project options -> Sessions tab) that automatically issues a GET request to `/output` each time after a request is issued to `/input`. I also configure the post request macro to replace the original response (from `/intput`) with the one from `/output`.

I also configure BurpBounty to inject some fixed value during active scan and check if the same value is present at the output. BurpBounty successfully detects this and creates an issue, that also includes the relevant Request-Response pair. The problem is that the Request displayed with the issue is the one sent to `/output` by the session handling rule, and not the one sent to `/input`, containing the releavnt payload.

I hope this clarifies things. If not please explain which exact part is unclear.

**Comment by wagiro** [comment]
Oks perfect, now I understand.

To solve it, I need to talk to you in a more fluid way, for example, through telegram? my nickname is @wagiro.

We connect through there and see how to solve it.

Thank you!

**Comment by v-p-b** [comment]
I'm available via Twitter DMs or GTalk under [@]buherator. Skype can work too...

**Comment by wagiro** [comment]
Due to the inactivity of the issue.
