### ISSUE TITLE
Grep - Match on Headers/body switch

### ISSUE THREAD

**Issue by Hipapheralkus** [wagiro/BurpBounty#3]
Very nice extender:)
I tried to use custom payloads for XSS, but these values were reflected in the HTTP response within the "x-request-path:" header.
Could there be an easy checkbox, whereas I want to search for payloads within headers, body, or both?
Thanks:)

**Comment by wagiro** [comment]
Hi @Hipapheralkus ,

Thanks for the issue!

Yes, it's a problem that I have identified. Sometimes the XSS are reflected in HTTP headers such as "Location" or the one you tell me.

I have planned this improvement, as you can see in the README, improvements for version 2.0:

* Search only in HTTP Headers
* Exclude HTTP headers from the search

As soon as I take some time, it will be the first thing that I implement.

Regards!

**Comment by wagiro** [comment]
Hi @Hipapheralkus ,

This features are already implemented! :D

The versión 1.2 is disponible, you can test it.

Thanks.
