### ISSUE TITLE
Suggestion to add logs files

### ISSUE THREAD

**Issue by Sy3Omda** [wagiro/BurpBounty#30]
https://github.com/wagiro/BurpBounty/blob/141846dd5742acaa8a65d67deffa3bc59ed9bf71/profiles/Linux-PathTraversal-MR.bb#L1

Hi ,
i see u r doing an amazing job here and i would like to suggest something.
could we add more than just `passwd` file to be detected.
for example logs file for linux as a start then windows if you could do it.
i will referance an article mentions those important log`s names in many different environment if you allow me.

[DistrosDefaultLayout](https://cwiki.apache.org/confluence/display/HTTPD/DistrosDefaultLayout)

**Comment by wagiro** [comment]
Hi @Sy3Omda !

Yes I will add others files, sure!

Thanks :)

**Comment by Sy3Omda** [comment]
> Hi @Sy3Omda !
> 
> Yes I will add others files, sure!
> 
> Thanks :)

check this out, I think I it would be a good addition 
https://github.com/Sy3Omda/burp-bounty
