### ISSUE TITLE
Problem with endpoint extractor

### ISSUE THREAD

**Issue by Lokillo20** [wagiro/BurpBounty#31]
I use burp 1.7.35 and scan check builder 3.0.5 beta, i have two problems:
 1- I can't save the modifications in profiles, i press save button but the changes not were saved. 
 2 - I trying to use the Endpoindextractor.bb but when it's loaded not work, i saw the code and nothing in the code is loaded, for example: 

`[{"Name":"EndpointsExtractor","Active":true,"Scanner":2,"Author":"@GochaOqradze","Payloads":[],"Encoder":[],"UrlEncode":false,"CharsToUrlEncode":"","Grep":["(?:\"|\u0027)(((?:[a-zA-Z]{1,10}://|//)[^\"\u0027/]{1,}\\.[a-zA-Z]{2,}[^\"\u0027]{0,})|((?:/|\\.\\./|\\./)[^\"\u0027\u003e\u003c,;| *()(%%$^/\\\\\\[\\]][^\"\u0027\u003e\u003c,;|()]{1,})|([a-zA-Z0-9_\\-/]{1,}/[a-zA-Z0-9_\\-/]{1,}\\.(?:[a-zA-Z]{1,4}|action)(?:[\\?|/][^\"|\u0027]{0,}|))|([a-zA-Z0-9_\\-]{1,}\\.(?:php|asp|aspx|jsp|json|action|html|js|txt|xml)(?:\\?[^\"|\u0027]{0,}|)))(?:\"|\u0027)"],"Tags":["endpoints","regex"],"PayloadResponse":false,"NotResponse":false,"TimeOut":"","isTime":false,"contentLength":"","iscontentLength":false,"CaseSensitive":false,"ExcludeHTTP":true,"OnlyHTTP":false,"IsContentType":false,"ContentType":"","NegativeCT":false,"IsResponseCode":false,"ResponseCode":"","NegativeRC":false,"MatchType":2,"RedirType":0,"MaxRedir":0,"payloadPosition":1,"payloadsFile":"","grepsFile":"","IssueName":"EndpointsExtractor","IssueSeverity":"Information","IssueConfidence":"Firm","IssueDetail":"Regex by Gerben_Javado : \n\u003cbr\u003ehttps://github.com/GerbenJavado/LinkFinder/blob/master/linkfinder.py\n\n\u003cbr\u003e\u003cbr\u003eEndpoints: \u003cbr\u003e\u003cgrep\u003e","RemediationDetail":"","IssueBackground":"","RemediationBackground":"","Header":[],"VariationAttributes":[],"pathDiscovery":false}]`

In the plugin only see: 
![Captura de pantalla (2)](https://user-images.githubusercontent.com/48301463/60757227-22634d00-9fde-11e9-9470-26ebe73ca01f.png)

and all empty boxes: 
![Captura de pantalla (3)](https://user-images.githubusercontent.com/48301463/60757261-b8977300-9fde-11e9-9783-b96c2472eccf.png)

I read the newest version of the plugin work on burp 2.0 probably it's not support olders versions. 

Regards! and I love your work, i hope my issue improve it.

**Comment by wagiro** [comment]
Hi Lokillo!

For the one problem:

1- I can't save the modifications in profiles, i press save button but the changes not were saved.

Are you selected first the profiles directory?

The secon problem I will see next monday.

Regards and thanks!

**Comment by Lokillo20** [comment]
hi! Yes i loaded all the profiles in the directory. Then I select a profile, for example, endpointextractor, i modify some boxes, i press save button, and automatically send me to the first profile (in my case is "Access Token by @egarme", but the endpointextractor profile is all empty.

**Comment by Lameh4ck3r** [comment]
i installed the extension but i cant see that tab

**Comment by wagiro** [comment]
Hi @Lameh4ck3r ,

Seems that the extension have a problem with windows systems, soon I will publish a release with this bug solved.

Thanks!
