### ISSUE TITLE
Space in Payload is getting replaced with +

### ISSUE THREAD

**Issue by havocuser** [wagiro/BurpBounty#32]

**Comment by havocuser** [comment]
Hi wagiro,

Space in Payload is getting replaced with + 
Please can you suggest how we can prevent it. We need Space in payload.

Thanks in advance.

Thanks and Regards,
Karibasavaraj K

**Comment by wagiro** [comment]
Hi @havocuser!

You can replace space with whatever you want on "Match and replace" feature. For example, replace space by %20, etc

Regards.

**Comment by havocuser** [comment]
Hi wagiro,

Tried the same. 
We are not able to get space in payload. But we get %20 characters in payload.

Please can you suggest. 

Thanks in advance.

Thanks and Regards,
Karibasavaraj K
