### ISSUE TITLE
Possible bug in status code filter

### ISSUE THREAD

**Issue by leesoh** [wagiro/BurpBounty#33]
First off, thank you for building this terrific extension!

I'm trying to tighten up my rule for testing for the absence of a CSP header and am running into issues. It was working as expected until I added a filter for status code. No matter what I put in here (single value, comma-delimited list), the check does not fire.

Here's what I've got set:

![image](https://user-images.githubusercontent.com/1276654/61137091-03ebce80-a482-11e9-93d4-be0c599450b2.png)

I haven't had the time to dig through the source yet but wanted to open an issue in the meantime.

**Comment by wagiro** [comment]
Hi @leesoh 

Sorry for the delay, I was on holidays.I will look and I tell you.

Thanks!

**Comment by wagiro** [comment]
Solved in new version.

Thanks :)
