### ISSUE TITLE
GUI Scroll Bug

### ISSUE THREAD

**Issue by electroxero** [wagiro/BurpBounty#34]
Hi, I'm using Burp V2.1, and after installing the latest version of Bounty Burp I have this problem.
![image](https://user-images.githubusercontent.com/20456461/61203057-9b9f2600-a6e9-11e9-80b3-818bc2272687.png)

It seems that all tabs have the same fixed length, but some of them like the "Profile Definition" need more space.

**Comment by wagiro** [comment]
Hi @electroxero 

Thanks for the issue, I will look and solve in next version.

Thanks!
