### ISSUE TITLE
Problem with triggering "Active Scan" payloads

### ISSUE THREAD

**Issue by adon90** [wagiro/BurpBounty#38]
Hello, I have an "active scan" profile, and, it works when I scan with all the issues selected:

![Burp-Bounty](https://user-images.githubusercontent.com/7115563/62947179-59e5c600-bde2-11e9-82aa-e169e81833e6.png)

However, if I remove all the "issues" the profile payloads don't trigger, neither if I just select "SQL injection".

![Bounty-Hunter-2](https://user-images.githubusercontent.com/7115563/62947472-dc6e8580-bde2-11e9-8f8c-a9bf507d4213.png)

So my question is: which issue corresponds the profile to make the it work? Do I need to select every issue? Thank you very much!

**Comment by wagiro** [comment]
Hi Adon90!

You need active "extension provided" issues, I think that is the last in the list.

Regards!

**Comment by adon90** [comment]
Yes, you are right, thank you so much @wagiro ;)
