### ISSUE TITLE
How to use this extension with BurpSuite Pro v1.73.x

### ISSUE THREAD

**Issue by dpnishant** [wagiro/BurpBounty#39]
Can we use this extension with Burp Suite Pro v 1.73.x?

**Comment by wagiro** [comment]
Hi!

Yes, you can use it. The extension usage Its the same for 1.7.X.

Regards.

**Comment by dpnishant** [comment]
@wagiro Thanks for the super fast response. I did install the extension with 1.73.x and it works fine. But I was confused because I could not find the "Audit checks - extensions only" option in the BurpSuite Pro's Active Scan configuration as seen in your demo videos. However I found that "Extension generated issue" (0x08000000) is the equivalent. Thanks for the great tool by the way. Very helpful :)
