### ISSUE TITLE
Not an issue, but have some questions.

### ISSUE THREAD

**Issue by Comodooo** [wagiro/BurpBounty#41]
Hi (again), 

Was just wonder, after going through some of you videos, if the collaborator is always on? Some videos has the "Collaborator button" and in the usage that button is gone. From my experience the collaborator url is only generated after I open the window inside of burp, or am I missing something here?

Also I was wondering if I execute a active scan against a target will "ALL" of my profiles that has the "Active" flag shot off against the target (and that are present in the profile directory?

Thanks again btw for the quick response and a wonderful tool!

**Comment by wagiro** [comment]
Hi!

> Was just wonder, after going through some of you videos, if the collaborator is always on? Some videos has the "Collaborator button" and in the usage that button is gone. From my experience the collaborator url is only generated after I open the window inside of burp, or am I missing something here?

Yeah, when {BC} token is detected, the Collaborator just start.


> Also I was wondering if I execute a active scan against a target will "ALL" of my profiles that has the "Active" flag shot off against the target (and that are present in the profile directory?

Yes :)


Regards.

**Comment by Comodooo** [comment]
So will I have the interaction of a new window popping up or will it just run in the "background"? 

Ah oh, explains a lot, was wondering why I had like 1000 payloads just running mayham haha.

**Comment by wagiro** [comment]
> So will I have the interaction of a new window popping up or will it just run in the "background"?

Yes the burpcollaborator are running in background.

> Ah oh, explains a lot, was wondering why I had like 1000 payloads just running mayham haha.

heheh ;)

**Comment by Comodooo** [comment]
Ah ok perfect, then I think I'm all set to go then. Thanks so much again for the quick respons! 

BR
