### ISSUE TITLE
add new features in the burpbounty

### ISSUE THREAD

**Issue by mohammed-sec2010** [wagiro/BurpBounty#42]
Change request method

For requests, you can automatically switch the request method between GET and POST, with all relevant request parameters suitably relocated within the request. This option can be used to quickly test the application's tolerance of parameter location, e.g. to bypass input filters or fine-tune a cross-site scripting attack.  can you please add this a new feature in BurpBounty that we can change from POST to Get automatically to find more bugs?

**Comment by wagiro** [comment]
Hi @mohammed-sec2010 !

The "Change request method" is a cool feature, but now I haven't time, maybe in a future :)

BR

**Comment by wagiro** [comment]
Hi @mohammed-sec2010 !

In a near future I will implement this.

Thanks.
