### ISSUE TITLE
payloads leads to freez the burpsuite

### ISSUE THREAD

**Issue by mohammed-sec2010** [wagiro/BurpBounty#43]
Hi
I created a new profile and insert these payloads:
<div onpointerover="alert(45)">this is onpointerover=alert(45)</div>
<div onpointerover="alert(45)">Mohamed(45)</div>
<div onpointerdown="alert(45)">Mohamed(45)</div>
<div onpointerenter="alert(45)">Mohamed(45)</div>
<div onpointerleave="alert(45)">Mohamed(45)</div>
<div onpointermove="alert(45)">Mohamed(45)</div>
<div onpointerout="alert(45)">Mohamed(45)</div>
<div onpointerup="alert(45)">Mohamed(45)</div>
<div onpointerover="alert(45)">Mohamed(45)</div>
<div onpointerdown="alert(45)">Mohamed(45)</div>
<div onpointerenter="alert(45)">Mohamed(45)</div>
<div onpointerleave="alert(45)">Mohamed(45)</div>
<div onpointermove="alert(45)">Mohamed(45)</div>
<div onpointerout="alert(45)">Mohamed(45)</div>
<div onpointerup="alert(45)">Mohamed(45)</div>
<object onafterscriptexecute=confirm(0)>
<object onbeforescriptexecute=confirm(0)>
then I scan url  and saw the burpsuite is freezed ,also I saw the cpu and ram is very high and I can not use the burpsuite

**Comment by mohammed-sec2010** [comment]
`<div onpointerover="alert(45)">this is onpointerover=alert(45)</div>
<div onpointerover="alert(45)">Mohamed(45)</div>
<div onpointerdown="alert(45)">Mohamed(45)</div>
<div onpointerenter="alert(45)">Mohamed(45)</div>
<div onpointerleave="alert(45)">Mohamed(45)</div>
<div onpointermove="alert(45)">Mohamed(45)</div>
<div onpointerout="alert(45)">Mohamed(45)</div>
<div onpointerup="alert(45)">Mohamed(45)</div>
<div onpointerover="alert(45)">Mohamed(45)</div>
<div onpointerdown="alert(45)">Mohamed(45)</div>
<div onpointerenter="alert(45)">Mohamed(45)</div>
<div onpointerleave="alert(45)">Mohamed(45)</div>
<div onpointermove="alert(45)">Mohamed(45)</div>
<div onpointerout="alert(45)">Mohamed(45)</div>
<div onpointerup="alert(45)">Mohamed(45)</div>
<object onafterscriptexecute=confirm(0)>
<object onbeforescriptexecute=confirm(0)>`

**Comment by mohammed-sec2010** [comment]
sorry I can not insert these payloads here: I upload it here
[xssTest.txt](https://github.com/wagiro/BurpBounty/files/3529588/xssTest.txt)

**Comment by wagiro** [comment]
Hi @mohammed-sec2010 !

Thanks for the issue, I will analyze it and tell you.

BR

**Comment by mohammed-sec2010** [comment]
![Captur2e](https://user-images.githubusercontent.com/11797933/63636170-8caa7c80-c674-11e9-87cb-57a36f92c442.PNG)
![1e](https://user-images.githubusercontent.com/11797933/63636171-8fa56d00-c674-11e9-9801-c6ddcae7449a.PNG)

also, the BlindSQLi-TimeBased payloads is executed and take 25 sceconds but the problem there is no notification issue  that the the timeout is exceeds 20 .

**Comment by wagiro** [comment]
Hi @mohammed-sec2010 ,

Thanks for the issue!

Best regards.
