### ISSUE TITLE
CRLF-Attack.bb fix false positive

### ISSUE THREAD

**Issue by ghsec** [wagiro/BurpBounty#44]
Hello Edu. I notised that when I use CRLF-Attack.bb I get more false result.
for fixing this need

Payload:  %0D%0ASet-Cookie:%20mycookie=myvalue # there I add %20
Response regex: ^Set-Cookie:\smycookie=myvalue  # 
It is 100% better and we don't get false.

**Comment by wagiro** [comment]
Hi @ghsec !

Thanks for this recommendations. I will change it.

Best regards.
