### ISSUE TITLE
使用burpbounty无法检测sqli

### ISSUE THREAD

**Issue by laowang1026** [wagiro/BurpBounty#45]
![image](https://user-images.githubusercontent.com/45323129/68366786-1e536180-016f-11ea-81b2-be4dbef3c47a.png)
![image](https://user-images.githubusercontent.com/45323129/68366801-26130600-016f-11ea-8f0f-a7953e19a868.png)

**Comment by wagiro** [comment]
Hi @laowang1026 !

Have you created a profile that detect that string in the response?

Best regards,
Thanks.
