### ISSUE TITLE
Scan Check Builder not working on version v1.7.37 Pro

### ISSUE THREAD

**Issue by manasmbellani** [wagiro/BurpBounty#46]
I am using Java v1.8.201 and I am using Scan Check Builder v3.0.5beta from the Bapp store. Even creating a simple profile to look for character 'a' in a passive response is not yielding any result.

See below: -

<img width="1052" alt="Screen Shot 2019-12-08 at 12 53 00 am" src="https://user-images.githubusercontent.com/2260634/70375721-4e9c4480-1955-11ea-9e4f-ae0023c17b92.png">

<img width="1039" alt="Screen Shot 2019-12-08 at 12 51 09 am" src="https://user-images.githubusercontent.com/2260634/70375724-5360f880-1955-11ea-8d81-ccf2632150bc.png">

**Comment by wagiro** [comment]
Hi @manasmbellani !

Do you still have the same problem? You are the only informed me of this problem, the rest does work for them.

I will soon release version 3.1 to see if it works for you.

Thanks,
Best regards.

**Comment by Lameh4ck3r** [comment]
![image](https://user-images.githubusercontent.com/35825039/83755405-29ca2500-a68b-11ea-9a2e-f643a4962582.png)
its not working

**Comment by Lameh4ck3r** [comment]
burpbounty v 3.2

**Comment by WorldHack666** [comment]
same here V 2020.4 also not working

**Comment by wagiro** [comment]
Hi,

Are you using windows system?

what version of Burp Bounty?

Thanks!

**Comment by WorldHack666** [comment]
windows 10 and burpbounty V3.3 with burpsuite 2020.4 showing some type of java unknown source error

**Comment by wagiro** [comment]
Can you show me the error?

**Comment by WorldHack666** [comment]
[
![Screenshot (67)](https://user-images.githubusercontent.com/25581871/84734679-33268c00-afbf-11ea-854f-52cde4e9a024.png)
](url)

**Comment by wagiro** [comment]
Hi @WorldHack666 !

This error maybe its because the jar file not is in this path. Can you test it?

Thanks.

**Comment by wagiro** [comment]
Hi @Lameh4ck3r !

Can you use the last version of Burp Bounty? 3.3, because they solved a bug in windows systems.

Thanks!

**Comment by WorldHack666** [comment]
i am using latest 3.3 and both kali and windows it doesn't working

**Comment by wagiro** [comment]
Are you sure that the .jar exist and its valid in the path that you can try upload the extension? Just to be sure, because your error appears when you try to load a .jar file that doesn't exist.

**Comment by WorldHack666** [comment]
In windows it's not opening and kali it's working but not loading profiles

**Comment by wagiro** [comment]
Hi all!

Can you write me through telegram, @wagiro ?

Thanks!
