### ISSUE TITLE
Passive Response based on Request params ?

### ISSUE THREAD

**Issue by ludooo** [wagiro/BurpBounty#48]
Let say I want to do a CRLF passive scan like this:

IF Request param Name $1 (GET or POST) IS equal to this Response regex "Set-Cookie: $1=value"

How can I do this, is it possible without an Active scan?

**Comment by wagiro** [comment]
Hi @ludooo !

Currently it not possible without an active scan. Passive scanning only searches for patterns in requests or responses but does not interact with them.

Thank you,
Best regards.
