### ISSUE TITLE
Null tags can be added

### ISSUE THREAD

**Issue by HannahLaw-Portswigger** [wagiro/BurpBounty#51]
We've come across an issue in your BApp Store Extension, Scan Check Builder.

You are allowing null tags to be added when you click ‘Add’ next to the empty dropdown.

How to reproduce:
- Install and go to scan check builder
- Set the profiles directory at the top to a directory of your choice
- Populate the name and author fields with test data
- Switch to ‘Tags’ tab
- Click ‘Add’ when nothing is in the drop down selector
- Click ‘Save’ button
- If you go to the profiles directory you chose, there should be a file created with a .bb extension
- Open the file and there will be some JSON
- There should by a “Tags” attribute with a list containing a null
- Close and reopen Burp
- Notice that the tab does not re-appear

There is a workaround available - go to the config file and delete the nulls from the Tags list or delete the config file and let them create their config again.

Would it be possible for you to provide a fix so that null tags cannot be added in the first place?

**Comment by wagiro** [comment]
Hi @HannahLaw-Portswigger !

Thanks for the issue. Solved.

Best regards.
