### ISSUE TITLE
Scan Check Builder not working on version v1.7.37 & 2.X.X

### ISSUE THREAD

**Issue by Nexsus1985** [wagiro/BurpBounty#52]
Hi,

I spent many hours trying to make it work without success. 
I have tested many versions from Java v1.8.X  and I am using Scan Check Builder v3.0.5\6.
Most of the time scanner not yield anything in PASSIVE mode and when I using ACTIVE mode, its not firing any payloads.
It is only send the payloads when I using the default profiles.
If I try to make a new profile from scratch or even change any exist profile, it stop work.

Another bug:
In profile definition and in profile manager when I try to customize or change an exist profile, it become duplicated in profile manager, If I try to delete a profile from the button (Remove) its not work at all.

Last thing, I didnt receive any bugs from Java or from the output in the extender.

Thanks.

**Comment by wagiro** [comment]
Hi @lopa17685 !

Does the error keep happening to you? because I haven't had any more complaints about that ...

Thank you,
Best regards.

**Comment by lopa17685** [comment]
Hi Wagiro,

Its strange, I tested it on 3 different computers and I receive the same behavior.
I can create a short video that will demonstrate the problem, basically it ends with with strange bugs that the functions not work well, event the default profile not firing all the time in Active mode and on Passive mode it not yield anything most of the time (inconsistent behavior).
Im currently using with burp pro (latest version) with java jre1.8.0_241 on windows 10 (virtual machine).
Beside that, the idea of this extensions is great :)

**Comment by wagiro** [comment]
Hi @lopa17685, 

Can you show me the video??

Thanks.

**Comment by lopa17685** [comment]
Sure, ill work in tomorrow and will upload it.

Thanks.

**Comment by wagiro** [comment]
Meanwhile...can you test the next version? maybe its solved your problem: 

https://drive.google.com/file/d/1NKL63VOXEfV2c36Fg5036tkcE7jtnQvc/view?usp=sharing

Thanks!

**Comment by wagiro** [comment]
Meanwhile...can you test the next version? maybe its solved your problem:

https://drive.google.com/file/d/1O9QiaGhlO5Q3uZAEo7ZQsEW6zKlyVGRl/view?usp=sharing

Thanks!

**Comment by Nexsus1985** [comment]
Hi Wagiro,

Sorry for the delayed, I had some arrangement that I had to finish.
I tested deeply the 3.1 version, I'm writing to you all the bugs that I experienced with screenshots and videos.
---Please send me your email so ill send you the videos (it contains sensitive data and that not need to be shared)----

	Bugs in Profiles:
1.	Can’t delete profile from the tab “Profile Manager”, nothing happens if I press on the button Remove.

2.	From some reason, after I created a profile, it got duplicated and I can’t delete it from the tabs, also I can’t find it in the folder (where all my profiles located)
-	Even if I restart the extension or burp and reload the profile from the directory, this behavior is occurred.

	Bugs in Scans
1.	Active Scan – It seems that the scan isn’t work, the payloads not firing at all or it fires only partial (event not in the same order).
-	Attach is a video that demonstrate the problem.
-	Tested with custom profiles (that I created) and profiles from git
-	Attached File: “Active Scan not works - Strange Behavior”

2.	Passive Scan – I tested with passive sqli profiles for a site that is vulnerable with SQLI.
-	Repeater – Burp bounty didn’t trigger the error
-	Proxy – Successfully triggered the error
-	Scanner – The most important part – Not Triggered the SQLI Event
o	Only the BURP scanner triggered the event
-	Attached File: “Active Profiles Scan - Not trigger SQLI”


![Cant Remove Profiles + Duplicate Profiles (sections 1,2)](https://user-images.githubusercontent.com/12773387/78983528-0cfeee80-7b2d-11ea-9bb6-6caa8c59606c.PNG)

**Comment by wagiro** [comment]
Hi @Nexsus1985 !

Thanks for all comments, my email is wagiro@gmail.com and my telegram its @wagiro.  If you prefer we can discus there.

Best regards.
