### ISSUE TITLE
Checks only one regex on a page although a list is given 

### ISSUE THREAD

**Issue by nerrorsec** [wagiro/BurpBounty#53]
It only gets one regex find although there are more.

**Comment by nerrorsec** [comment]
I had a file with a aws url and jwt token and used two regex in a profile.
This is only giving me match on aws url. The regex is working fine, I checked using only jwt regex.

**Comment by wagiro** [comment]
Hi @nerrorsec !

This is the normal behavior, with regex you can put two regex in one. But if you want find two different things, maybe you can create two different profiles.

Thanks,
Best regards.

**Comment by nerrorsec** [comment]
Thanks for the info. I was doing it wrong all this time.

**Comment by wagiro** [comment]
By the way @nerrorsec today or tomorrow I will publish new version with some bugs corrected and better performance. Thanks!

**Comment by nerrorsec** [comment]
Looking forward to it.
:-)

**Comment by nerrorsec** [comment]
Also, does character escaping matters on the regex?

**Comment by wagiro** [comment]
The search for the regular expression is done directly with:

```java
p = Pattern.compile(grep);
m = p.matcher(requestString);
```

**Comment by nerrorsec** [comment]
Thanks.
