### ISSUE TITLE
Important feature to add - Automate scans by passively trigger active payloads based on conditions

### ISSUE THREAD

**Issue by Nexsus1985** [wagiro/BurpBounty#55]
While crawling, passively trigger active payloads based on conditions >>> Example: While I perform the crawling process, it will fire payloads based on the conditions (such as SQLI payloads against each parameter or path discovery, etc.

In the photo (from other extension) you can see that I match again all param values and replace them with XSS payload.
The process is performed automatically via crawling or other scan methods.

![image](https://user-images.githubusercontent.com/12773387/79222428-291dcb00-7e60-11ea-834c-457fb15d654d.png)

Thanks.

**Comment by wagiro** [comment]
Hi,

Yes sure, In the future when I have more time I will implement it.

Thanks.

**Comment by wagiro** [comment]
I have implemented it :)
