### ISSUE TITLE
When using domxss attack payload, the plug-in is not recognized

### ISSUE THREAD

**Issue by laowang1026** [wagiro/BurpBounty#58]
Hi, kind regards, when using domxss attack payload, the plugin does not recognize

![image](https://user-images.githubusercontent.com/45323129/80302374-3e89e200-87dc-11ea-9e80-72af6a40ca0c.png)
![image](https://user-images.githubusercontent.com/45323129/80302380-46498680-87dc-11ea-8760-32367d598f0c.png)
![image](https://user-images.githubusercontent.com/45323129/80302430-96c0e400-87dc-11ea-955a-3dd9a13a6539.png)
![image](https://user-images.githubusercontent.com/45323129/80302447-adffd180-87dc-11ea-9419-060ef7ef3055.png)

**Comment by wagiro** [comment]
Hi @laowang1026 !

That's not a DOM XSS issue:

* https://owasp.org/www-community/attacks/DOM_Based_XSS

But you can solve this, you can change "Match Type" to Simple String, because your payload it's not a regex.

Thanks! :)
