### ISSUE TITLE
How to add the profiles in burp?

### ISSUE THREAD

**Issue by marcelo321** [wagiro/BurpBounty#59]
Hello, sorry for this issue. How do i add the cool profiles to the my empty list of profiles in burp? I don't even understand how to add them manually one by one.

**Comment by wagiro** [comment]
Hi @marcelo321 !

You can talk with me on telegram @wagiro , and I will help you to create new profiles.

Best regards!

**Comment by SummerSec** [comment]
hi, i cannot talk with u in telegram, so u can chat @secsummer ?

**Comment by SummerSec** [comment]
i meet this issue too
