### ISSUE TITLE
Feature Request: Add append/replace for all payloads and timing option

### ISSUE THREAD

**Issue by 1N3** [wagiro/BurpBounty#6]
Hey man, really like the plugin! 

After using it for a bit, 2 things that would really improve the usefulness of the tool are:

1. Have an option to append AND/OR replace all payloads to existing URL's/parameters
2. Have a timing option in seconds to check for timing attacks (ie. ' OR SLEEP(5)--), if response is greater than 5 seconds, indicate a vulnerability.

**Comment by wagiro** [comment]
Hey 1N3!

thank you for the recommendations!

Currently I'm improving with other extension utilities, staying like this:

![burpbounty-1 4](https://user-images.githubusercontent.com/3398430/41544831-fe918190-7319-11e8-8ecc-a5e3a6e2f1ae.png)

As soon as I have these improvements, I'll start with yours. Can you give me an example of the point 1 of your recommendations?

Regards!

**Comment by 1N3** [comment]
Yeah, so let's say a URL I'm scanning with the plugin is as follows:

https://site.com/users.php?id=1

Currently, the plugin replaces the values for id=1 with whatever payload I provide (ie. ' or '1'='1'--, etc.). It would be helpful in some cases to keep the origin value in tact and append the payloads is you would have https://site.com/users.php?id=1' or '1'='1'--. Burp Intruder already includes an option for this under the Intruder menu. 

If there was a checkbox for "Append" and a checkbox for "Replace", it would give the users the option to append the payloads to existing values or replace them completely. 

Also glad to see that redirections are being implemented as well. I was going to request the same 👍

**Comment by wagiro** [comment]
Hi 1N3,

I closed the issue by mistake. As soon as I have implemented what you tell me, I will close it.

Too bad we do not have more time to implement faster!

Regards!

**Comment by 1N3** [comment]
No worries. Look forward to the next releases.

**Comment by egarciamelia** [comment]
Hi @1N3 !

I have programmed this feature :D 

![burpbounty_1 6](https://user-images.githubusercontent.com/31238463/47150453-ed3f8f00-d2d6-11e8-81e9-fbf5f11169d6.png)


Soon it will be available, as soon as I make another improvement, I will publish version 2.0 with many improvements.

- Redirects
- Payloads replace/append
- Payload and greps associated with files
- Encode space
- Negative match for content-type and Response code

And the option that I am making:
- BurpCollaborator support.

Cheers!

**Comment by wagiro** [comment]
Hi @1N3 !

I have programmed this feature :D 

![burpbounty_1 6](https://user-images.githubusercontent.com/31238463/47150453-ed3f8f00-d2d6-11e8-81e9-fbf5f11169d6.png)


Soon it will be available, as soon as I make another improvement, I will publish version 2.0 with many improvements.

- Redirects
- Payloads replace/append
- Payload and greps associated with files
- Encode space
- Negative match for content-type and Response code

And the option that I am making:
- BurpCollaborator support.

Cheers!

**Comment by 1N3** [comment]
Nice man! Can't wait to test it out!
