### ISSUE TITLE
Modify X-XSS-Protection profile to do the oposite 

### ISSUE THREAD

**Issue by calabacito** [wagiro/BurpBounty#61]
Now it is checking if the flag is present. It should do the oposite, the flag should NOT be used:

https://github.com/OWASP/CheatSheetSeries/issues/376#issuecomment-603370156

Keep the great work :)

**Comment by wagiro** [comment]
Hi @calabacito ,

Thanks for the issue. The actual X-XSS-Protection profile, looks if the "X-XSS-Protection: 1;" header it's not present on the response.

![image](https://user-images.githubusercontent.com/3398430/83971891-bff58980-a8dd-11ea-8e8d-9cdf9e809c9d.png)

Best regards.
