### ISSUE TITLE
BurpBountyExtension line 174: Index: 16, Size: 16

### ISSUE THREAD

**Issue by viho-chen** [wagiro/BurpBounty#66]
BurpSuite version:v2.1.06
BurpBounty version: v3.3
Site: http://127.0.0.1/bWAPP/sqli_1.php?title=&action=search
OS:mac

please help .i can't run this plugin on  the Mac. But it works correctly on  my Windows

![image](https://user-images.githubusercontent.com/49968562/84871618-57fc2b80-b0b3-11ea-88d2-9ffa33fa3cd9.png)

thks!

**Comment by wagiro** [comment]
Hi @viho-chen !

Have you download the last jar version??

I upload yesterday a modified version.

Thanks.
