### ISSUE TITLE
match type = payload , 是否还没实现该功能？

### ISSUE THREAD

**Issue by a0xpg** [wagiro/BurpBounty#67]
hi，我在测试xss，发现代码没有实现该功能，是否还在实现中？

**Comment by wagiro** [comment]
Hi!

Yes, GenericScan line 173:

 if (matchtype == 3) {
                    greps = payloads;
                }

If you want, we can talk trough telegram, my nickname is @wagiro , or by twitter @burpbounty

Thanks!

**Comment by jeremychoi** [comment]
@wagiro  could you confirm if it's working with version 3.4? i think it(setting 'payload' matchtype) worked before but it doesn't seem so any more. 'simple' type + strings for 'grep' is working though.

**Comment by jeremychoi** [comment]
since this is already a closed issue. I opened new one: https://github.com/wagiro/BurpBounty/issues/70
