### ISSUE TITLE
about grep.split

### ISSUE THREAD

**Issue by a0xpg** [wagiro/BurpBounty#68]
at GenericScan.java  line: 556

if match type = Regex and if grep value has ","
grep.split(",")[2] 会截断grep

eg： "Grep":["true,Or,\\b(13[0-9]|14[5-9]|15[0-3,5-9]|16[2567]|17[0-8]|18[0-9]|19[13589])\\d{8}\\b"]
grep.split(",")[2] = "\\b(13[0-9]|14[5-9]|15[0-3"

so，==> String[] tokens = grep.split(",",3);

**Comment by wagiro** [comment]
Hi @a0xpg !

Thanks for suggestion, changed!
