### ISSUE TITLE
Sql injaction & XML_External_Entity_(XXE) payloads are not working in burp v1.7.35 

### ISSUE THREAD

**Issue by mohammed-sec2010** [wagiro/BurpBounty#7]
Hi
 I use your tool  and the problem is Sql injaction & XML_External_Entity_(XXE) payloads does not working in burp v 1.7.35

**Comment by virusvfv** [comment]
I found that if U check checkbox "Exclude HTTP Headers" then burpbounty will NOT create issues about SQLi, but if U uncheck this - SQL issues will be created...
This bug was tested in burp 1.35 and OWASP mutillidae latest version.

**Comment by wagiro** [comment]
Hi @mohammed-sec2010 @virusvfv can you give me an example when the tool don't run, for debbug?

Thanks!

**Comment by saifsaiyed1919** [comment]
yesterday morning i used .onion(Dark Web) web hack SQL injection in Kali linux but these critical website. I failed
