### ISSUE TITLE
payload matchtype is not working with v3.3 and v3.4

### ISSUE THREAD

**Issue by jeremychoi** [wagiro/BurpBounty#70]
'payload' matchtype isn't working with version 3.3 and 3.4, for example for the XSS.bb profile.

I confirmed it is working with v3.2, using the jar file which is found in the release.

 'simple' type + strings for 'grep' is working though.

**Comment by wagiro** [comment]
Hi Jeremy!

This bug is known for me, and I solved in Pro version. In Free version soon I will publish new update with this issue solved :D

It is because I changed the detection algorithm and did not modify the "payload" and "payload encoded" matchtype. It is solved in GenericScan.java with the code:

```
            if (!encoders.isEmpty()) {
                switch (matchtype) {
                    case 1:
                        payloadsEncoded = processPayload(payloads, encoders);
                        payloads = new ArrayList(payloadsEncoded);
                        break;
                    case 2:
                        payloadsEncoded = processPayload(payloads, encoders);
                        payloads = new ArrayList(payloadsEncoded);
                        break;
                    case 3:
                        payloadsEncoded = processPayload(payloads, encoders);
                        greps = new ArrayList();
                        for (String p : payloads) {
                            greps.add("true,Or," + p);
                        }
                        payloads = payloadsEncoded;
                        break;
                    case 4:
                        greps = new ArrayList();
                        payloadsEncoded = processPayload(payloads, encoders);
                        for (String p : payloads) {
                            greps.add("true,Or," + p);
                        }
                        payloads = new ArrayList(payloadsEncoded);
                        break;
                    default:
                        payloadsEncoded = processPayload(payloads, encoders);
                        payloads = new ArrayList(payloadsEncoded);
                        break;
                }

            } else {
                if (matchtype == 3) {
                    for (String p : payloads) {
                        greps.add("true,Or," + p);
                    }
                }
            }
```

Thanks for the issue,
Best regards.

**Comment by jeremychoi** [comment]
@wagiro thanks. BTW I tested it on Burp PRO. Do you mean that there is a separate Pro version of this scan check builder extension?

**Comment by wagiro** [comment]
Hi Jeremy!

Yes, but is not published yet. Is a very improved version, with a profesional pack of profiles and rules. Will be published soon, and will have a license by 59€/year.

Throughout the year I will be adding more profiles of the new CVEs and attack vectors that come out.

Stay informed on twitter:

https://twitter.com/BurpBounty

Best regards!
