### ISSUE TITLE
[Bug] Grep in regex mode is case sensitive

### ISSUE THREAD

**Issue by Haones** [wagiro/BurpBounty#72]
If you use match type **Regex** in the **Grep**, it ignores the Grep Option "Case sensitive". While being false, it didn't find `accessToken` string with regex rule in the profile `access[_-]?token(=| =|:| :)`, but when I changed it to `access[_-]?Token(=| =|:| :)` (capital "T") - rule worked.

**Comment by wagiro** [comment]
Solved, now the regex will compiled with Pattern.CASE_INSENSITIVE.

Thanks!
