### ISSUE TITLE
Not finding XSS

### ISSUE THREAD

**Issue by marcelo321** [wagiro/BurpBounty#75]
Hello!

I have a website where the vulnerable parameter reflects all input directly in html code. For some reason the XSS templates aren't detecting it. I don't know if that's normal or there is something wrong.

Basically if you inject <script>alert()</script> in the only paramter provided you have XSS, so I don't know where the scanner is failing.

**Comment by wagiro** [comment]
Hi @marcelo321 ,

Do you still have this problem?

Thanks,
Best regards.
