### ISSUE TITLE
Burp Suite Professional v2020.9.1

### ISSUE THREAD

**Issue by Mijobar** [wagiro/BurpBounty#77]
Does anyone have an issue using this extension in the new version of Burp Suite Professional v2020.9.1 ?

I am unable to get known findings from previous versions in this  new version. 

Thanks!

**Comment by Mijobar** [comment]
Update: We are thinking importing of the rules in a newer version removed the "})" at the end of the Regex.

**Comment by wagiro** [comment]
Hi @Mijobar ,

Could it be, do you still have the problem?

Thanks,
Best regards.
