### ISSUE TITLE
Able to edit payloads in profile

### ISSUE THREAD

**Issue by virusvfv** [wagiro/BurpBounty#8]
We are able to add, clear, remove payloads to profile, but not to edit them. 
Suppose, I importing some fuzzlist in profile and then i have to edit some payloads to correct them fo using..
Or it may be feature for auto-read payloads from txt files when plugin start. 

For example: I use some fuzzlist txt files, which I continuously update from time to time. 
If I could snap txt files to profiles in BurpBounty (for ex: XXEfuzz.txt to XXE profile, JsonFuzz.txt to JSON profile and so on) I would be excellent ! 

So this feature would be very usefull for bughuners. 

P.S. Thank U for such tool !

**Comment by wagiro** [comment]
Hi @virusvfv !

Thanks for your comments ;D

Now I'm on holidays, as soon as I get back to work, I start looking at it.

Regards!

**Comment by wagiro** [comment]
Hi @virusvfv, 

"If I could snap txt files to profiles in BurpBounty (for ex: XXEfuzz.txt to XXE profile, JsonFuzz.txt to JSON profile and so on) I would be excellent !" 

It's an excelent idea, in future version I see how I can implemented.

Thanks!

**Comment by wagiro** [comment]
Hi @virusvfv  !

I have programmed this feature :D 

![burpbounty_1 6](https://user-images.githubusercontent.com/31238463/47150453-ed3f8f00-d2d6-11e8-81e9-fbf5f11169d6.png)


Soon it will be available, as soon as I make another improvement, I will publish version 2.0 with many improvements.

- Redirects
- Payloads replace/append
- Payload and greps associated with files
- Encode space
- Negative match for content-type and Response code

And the option that I am making:
- BurpCollaborator support.

Cheers!
