### ISSUE TITLE
Add payload encoding on burp "nested insertion" way

### ISSUE THREAD

**Issue by nancheal** [wagiro/BurpBounty#85]
I found that the encoding used by burpbounty is buildUnencodedRequest, maybe add the encoding of buildRequest, like this https://forum.portswigger.net/thread/design-new-extension-problem-with-buildrequest-and-url-encode-5d4b35a6
Can solve more problems. Can this requirement be added?

**Comment by wagiro** [comment]
Hi @nancheal ! 

That post, Antoni, is me. I have implemented correctly and the payload is not encode if you dont want. Have you any problem with the encode?

Thanks.

**Comment by nancheal** [comment]
thanks for replay, i mean if the payload in "buildRequest" way, the feature(https://portswigger.net/burp/documentation/scanner/auditing#nested-insertion-points) will take effective(https://forum.portswigger.net/thread/design-new-extension-problem-with-buildrequest-and-url-encode-5d4b35a6) like a "auto encode" with burpsuite, but "buildUnencodedRequest" way may not Produces the above effect, would a "auto encode" will be possible? a big thanks

**Comment by wagiro** [comment]
Hi @nancheal,

The burp extender api has no method to implement this, this is done only by its native scanner. I will look to implement it in the future, thanks for the suggestion!

Best regards.

**Comment by nancheal** [comment]
@wagiro, thanks for accept this suggestion, I noticed that backslash-powered-scan (https://github.com/PortSwigger/backslash-powered-scanner) can request such an "auto-encode" request eyIxMjMxMiI6ImRhc2R3cWRxd2QkenE9JTNjJTYxJTYwJTI3JTIyJTI0JTdiJTdiJTVjJnpxd
which decoding is {"12312":"dasdwqdqwd$zq=%3c%61%60%27%22%24%7b%7b%5c&zq%3d"},
I think it should be this buildRequest (https://github.com/PortSwigger/backslash-powered-scanner/blob/master/src/burp/PayloadInjector.java#L113) make "auto encode" worked.
and the buildRequest wiki page(https://portswigger.net/burp/extender/api/burp/iscannerinsertionpoint.html) - "Note: Scan checks should submit raw non-encoded payloads to insertion points, and the insertion point has responsibility for performing any data encoding that is necessary given the nature and location of the insertion point." maybe the buildRequest can "auto encode", i guess
