### ISSUE TITLE
Agregate issues

### ISSUE THREAD

**Issue by virusvfv** [wagiro/BurpBounty#9]
Maybe BurpBounty would to aggregate issues when it create it. 
For example: if we have 3 payloads:
 admin' 
 admin' or '1'='1
 admin'\'\"
Burpbounty will create 3 issues with SQL injection.
Sometimes it is useful, but sometime are VERY VERY NOT.
So it may be some checkbox in form about aggregation so user can decide...

**Comment by wagiro** [comment]
Hi @virusvfv !

Same here, thanks!

**Comment by wagiro** [comment]
Hi! 

At the moment I do not plan to implement this feature.

Thanks!!
