### ISSUE TITLE
Bug: BB Profiles will Not Run if an Error is Encountered

### ISSUE THREAD

**Issue by a-marionette** [wagiro/BurpBounty#98]
I observed that if an error is encountered for a BB profile, the scanner will not finish iterating through the remaining BB profiles in the queue. This became apparent when I removed the problematic profiles causing the error (in this case, Null Issue Severity error as shown in the extension output console) and my other profiles ran successfully. 

I am not certain if an error will halt the execution of all profiles or just some but I can confirm my profile did not run after encountering the error.

**Comment by wagiro** [comment]
solved in burp bounty 4.0
